### ISSUE TITLE
DTS renamed?

### ISSUE THREAD

**Issue by nickdesaulniers** [linux-3ds/linux#12]
not sure if this was intentionally changed from xerpi's port or what, but it looks like the dts file is now named:

https://github.com/linux-3ds/linux/blob/master/arch/arm/boot/dts/ctr.dts

but the bootloader expects /linux/nintendo3ds_ctr.dtb.  I think it would be better to rename the dts back to nintendo3ds_ctr.dts, or at least fix firm_linux_loader to look for the new ctr.dtb.  Sure, you can rename the file when placing it on the sd card, but...

**Comment by Wolfvak** [comment]
yeah it should probably be renamed to nintendo3ds_ctr.dtb or nintendo_ctr.dtb, paths are easy to change in the bootloader anyway

for the new models we can change ctr to ktr
