### ISSUE TITLE
LGTM from paulguy

### ISSUE THREAD

**Issue by nickdesaulniers** [linux-3ds/linux#22]
I noticed two drivers have copyright from Paul LaMendola which I assume is @paulguy.  @paulguy, do you accept the [Linux kernel's Certificate of Origin](https://www.kernel.org/doc/html/latest/process/submitting-patches.html?highlight=signed%20off#developer-s-certificate-of-origin-1-1) so that we may upstream your changes for which you hold copyright?

**Comment by paulguy** [comment]
I dunno if any of the code that's left there is anything that involves me at all.  Not sure how to check but my contribution was back when the bottom screen was a kernel-controlled touch screen keyboard which doesn't seem the case anymore.  I will agree for the sake of simplicity if need be, otherwise if anything associated with me no longer exist I imagine I no longer hold any copyright on any part of the file?

**Comment by Wolfvak** [comment]
Your code is still pretty much verbatim from when you first introduced it, you added the kernel software keyboard in https://github.com/xerpi/linux_3ds/pull/1 (I had to make a few changes to accomodate for kernel updates).
The whole point of this is to make sure you're fine with us upstreaming the changes - of course, if you make it into the patches you'll also be added as an author.

**Comment by paulguy** [comment]
Oh, so it is I guess, heh.  I have no idea how to make it in to patches but yeah whatever I have to do to make the process go smoothly, I'm on board.

**Comment by Wolfvak** [comment]
Well you just need to agree explicitly to the first question. This is mostly a formality, just to make sure all the contributors are on the same page. After that is done I'll just close this issue.

**Comment by paulguy** [comment]
Ah ok.  Then, yes I have created the the code I wrote in whole and i have the right to submit it.

**Comment by Wolfvak** [comment]
can you add the signed off by thing? sorry to be annoying, that's just how it is

**Comment by paulguy** [comment]
I don't really know where to put it other than somehow resubmitting it as a patch again?  Sorry this is a pain from me.  I'm really not used to contributing to things or git or anything heh.

**Comment by Wolfvak** [comment]
nah, just post the comment again and add the signed off by at the end of the message

**Comment by paulguy** [comment]
Oh OK.

I have created the the code I wrote in whole and i have the right to submit it.

Signed-off-by: Paul LaMendola <paulguy119@gmail.com>

**Comment by Wolfvak** [comment]
awesome, thank you

**Comment by nickdesaulniers** [comment]
Thanks, good enough.
