### ISSUE TITLE
Wifi error

### ISSUE THREAD

**Issue by artus25200** [linux-3ds/linux#39]
when i start my 3ds on linux, there is this error: Starting Network : ip: RTNETLINK answers: Operation not supported FAIL
And it's annoying because i can't execute the wget command

I have a new 2ds XL and i downloaded linux from universal updater

![IMG_0770](https://user-images.githubusercontent.com/68189043/116039471-10e3ad00-a66b-11eb-8b4c-a564f2e2411b.JPG)

**Comment by Wolfvak** [comment]
The WiFi chip on the 3DS is not supported yet, you can check more info here https://github.com/linux-3ds/linux/wiki/Driver-and-platform-support

**Comment by NetherStar64** [comment]
How is it possible to get files onto the 3ds and store them(because after reboot They are lost)

**Comment by Wolfvak** [comment]
you can put them in your sd card and then mount it, the device is `/dev/vda`

**Comment by NetherStar64** [comment]
It throws with ```
F2FS-fs (vda): Magic Mismatch, valid(0xf2f52010) - read(0x0)
F2FS-fs (vda): Can't find valid F2FS filesystem in 1th Superblock
```*2

**Comment by Wolfvak** [comment]
well, you need to mount the partition that corresponds to your device, that would be perhaps vda1 or vda2?On Apr 28, 2021 16:48, NetherStar64 ***@***.***> wrote:
It throws with
F2FS-fs (vda): Magic Mismatch, valid(0xf2f52010) - read(0x0)
F2FS-fs (vda): Can't find valid F2FS filesystem in 1th Superblock
```*2


—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Wolfvak** [comment]
You need to mount the partition, not the device.
Also I just realized you're not the OP and you hijacked another issue, please open another issue if you need help
