### ISSUE TITLE
Mounting fails: Magic Mismatch

### ISSUE THREAD

**Issue by NetherStar64** [linux-3ds/linux#40]
Sorry for writing in the wrong issue.

Mounting either vda or vda1 throws the same error, there's no other partition

**Comment by Wolfvak** [comment]
What's the output of `fdisk -l`?

**Comment by NetherStar64** [comment]
```
Disk /dev/vda: 30GB, 31.....
3880 cylinders, 255 heads, 63 sectors/track

...
/dev/vda1 0,32,33   1023, 254, 63      2048    62332927        62330880   29.7G    c Win95 Fat32 (LBA)
```

**Comment by NetherStar64** [comment]
Oh okay I got it now with mount -t msdos. Sorry, I'm still learning. Thanks for your help
