### ISSUE TITLE
keyboard single quotes is actually comma

### ISSUE THREAD

**Issue by nickdesaulniers** [linux-3ds/linux#41]
trying to benchmark my cpufreq driver, I noticed I can't use single quotes in the shell. This is noticeable moreso if you long press RShf then hit the double quotes, `<` gets entered instead, which is the shifted version of comma.

**Comment by Wolfvak** [comment]
the 3DS has a resistive touchscreen, calibration points differ by individual consoles and it's been known to be pretty terrible for some.

try touching in the surrounding area, maybe you just have a really bad touchscreen?

**Comment by Wolfvak** [comment]
also, touchscreen calibration will eventually be necessary and I have no idea how it's specifically managed in the kernel (or in userspace) but I guess it'll be easy, we can grab the necessary data off the attached flash chip via spi, or just ask the user to calibrate the system

**Comment by nickdesaulniers** [comment]
I don't think this is miscalibration; I think the wrong input is sent via the driver.

**Comment by Wolfvak** [comment]
sorry, I misinterpreted your first message in another way, you're right
try changing the KEY_COMMA in this line https://github.com/linux-3ds/linux/blob/master/drivers/platform/nintendo3ds/ctr_codec.c#L97 to KEY_APOSTROPHE

if if works, you can open a PR to get it fixed
