### ISSUE TITLE
No desktop environnement

### ISSUE THREAD

**Issue by JeexyOof** [linux-3ds/linux#49]
The graphical interface doesn't show up after doing 
/sdmount.sh and /start-weston.sh
Im lock on a screen : 
(Its not my 3ds)
![image](https://user-images.githubusercontent.com/84280902/118402619-f2ba0d00-b66a-11eb-9f27-c9e3a57b4461.png)

**Comment by Wolfvak** [comment]
that kernel version (4.7.0-rc7) doesn't correspond with the tree present here?

not sure what you're doing

**Comment by JeexyOof** [comment]
@Wolfvak as i said, this is not my 3ds, i can't use mine today.

**Comment by ParzivalWolfram** [comment]
This is a very, VERY old version of this project. This is from 2 project
takeovers ago! We don't have a 100% working buildroot instance yet, so this
isn't doable as of now without knowing how to manually make a rootfs, but
I'm working on it as much as I have time for.

**Comment by Wolfvak** [comment]
good to see this cleared up then, will close
