### ISSUE TITLE
Wiki Improvements

### ISSUE THREAD

**Issue by Redcarred2** [linux-3ds/linux#51]
Some more needed packages for building are flex, libssl-dev, and bison
`
sudo apt install gcc-arm-linux-gnueabi binutils-arm-linux-gnu flex bison libssl-dev
`

**Comment by Redcarred2** [comment]
Also, Sorry about not figuring out labels, I barely use github

**Comment by nickdesaulniers** [comment]
thanks, I've added them.

**Comment by marius137** [comment]
sorry to reopen a closed issue, but the correct packege is `binutils-arm-linux-gnueabi`. Also `build-essential` is also required

**Comment by Wolfvak** [comment]
shouldn't it be enough to just bring in `gcc-arm-linux-gnueabi`? that one depends on the currently latest available gcc for arm, which in turn depends on binutils-arm-linux-gnueabi (at least on debian)

as for everything else, perhaps it'd be better to just list it as "usual kernel compilation requirements"? most distros have their own pages on this, like https://wiki.debian.org/BuildADebianKernelPackage, so we can simply say "fetch the required packages by your distro, plus the cross gcc armel toolchain, then follow the instructions here"

**Comment by marius137** [comment]
I tried it out with the latest debian docker image and I had to install both gcc and binutils. I will play with it a little bit tomorrow and will report back. If you don't hear from me, feel free to ping me

**Comment by marius137** [comment]
I put together a guide with all the requirements, build instructions and how to install it to your SD Card. Feel free to use it in your wiki!
https://gist.github.com/marius137/221747ea7648399b2a20e5cbc5b49e89

**Comment by Wolfvak** [comment]
sorry for the late reply, I'll try to splice this info into each repository and point the kernel wiki to the linux_loader one

**Comment by marius137** [comment]
If you want to, I can build a docker image that downloads the sources from git, builds everything and spits out the ready to use files.

**Comment by ParzivalWolfram** [comment]
That seems like overkill.

**Comment by Wolfvak** [comment]
yeah that does seem a bit too much, perhaps it'd be better to create a meta-repository that contains the others and a single build script that gets everything done

we can even add gh actions to it, in order to get more or less full releases, instead of telling people to go to at least 3 different repos gathering binaries or building projects

**Comment by marius137** [comment]
I created a build script. while it works and checks for dependencies, it does not yet check that firmtool is in $PATH and has no error checking https://gist.github.com/marius137/4205310639616c026b7c248854d4a6a1
