### ISSUE TITLE
use the initrd provided by the buildroot CI

### ISSUE THREAD

**Issue by Wolfvak** [linux-3ds/linux#53]
@kleo can you change it so the CI will always generate the kernel image with the always-latest rootfs found here https://github.com/linux-3ds/buildroot/releases ?

this is related to #52, and other issues I've found with the existing sc16is750 driver (gpio is added before initializing its data)

**Comment by kleo** [comment]
Done https://github.com/linux-3ds/linux/pull/54. I tested the build [here](https://github.com/kleo/linux/actions/runs/926847037) and I also tried booting on my 3DS

**Comment by Wolfvak** [comment]
awesome, thanks!

the only problem I can think of is artifacts only remain for 90 days in gh, so we need to update the Buildroot config within the next 3 months... I think we'll update it plenty of times before that :)
