### ISSUE TITLE
Won't boot on EU New Nintendo 3DS

### ISSUE THREAD

**Issue by niansa** [linux-3ds/linux#56]
--- FIRM Linux loader by xerpi ---
    Initializing SD card... success
    Loading linux/zImage...
    File linux/zImage loaded:
        size: 4389904 B
    Loading linux/nintendo3ds_ktr.dtb...
    File linux/nintendo3ds_ktr.dtb loaded:
        size: 8119 B
    Loading linux/arm9linuxfw.bin...
    File linux/arm9linuxfw.bin loaded:
        size: 6992 B

Then nothing happens anymore.

SD Card is clean, all checksums match the original.

**Comment by niansa** [comment]
Edit: took another sd card, did a clean flash, and bootet it all from that one. Still not working.

**Comment by niansa** [comment]
https://user-images.githubusercontent.com/20720267/123013184-053f0900-d3c4-11eb-8a58-8ada52f62fa9.mp4

**Comment by nickdesaulniers** [comment]
probably the same issue as https://github.com/linux-3ds/firm_linux_loader/issues/23

**Comment by ParzivalWolfram** [comment]
What initrd are you using, and can you try loading the FIRM from GodMode9? I've hit this issue a few times, and usually it means it ran out of RAM loading the initrd or somethibg similar.

**Comment by knuxify** [comment]
whoops, forgot to update my original comment :p

I tried removing downclock/upclock functions as suggested in this thread and the firm_linux_loader loading screen showed up as usual, but still didn't boot into Linux - same in fastboot3ds.

I'm assuming there might just be something wrong with my build, though - it doesn't have a built-in initramfs, only one loaded from the SD card with the code in #61 (and the equivalent firm_linux_loader patch).

I'll try the prebuilt images and the godmode9 suggestion, and report back.

**Comment by Wolfvak** [comment]
@niansa @knuxify can you test with the latest firm_linux_loader release? it should work correctly now

**Comment by ParzivalWolfram** [comment]
> Experiencing the same issue here. tried updating the loader but it still fails. its just a Mess of Pixels.

That doesn't tell us specifics, sadly, as the pixel mess staying around just means it failed to boot, you still see it during normal operation for a moment.

Have you tried the suggestion above your comment? Are you trying a newer or older build?

**Comment by Maximal98** [comment]
yes i have, to no avail. still not booting.

**Comment by shokifrend007** [comment]
@knuxify I had the same issue until I installed [arm9linuxfw](https://github.com/linux-3ds/arm9linuxfw). Make shure you have that.

**Comment by niansa** [comment]
Thanks!

**Comment by Wolfvak** [comment]
> Thanks!

Assuming this was a user error, closing
