### ISSUE TITLE
Any plans for an official development discord server

### ISSUE THREAD

**Issue by FreddyFeuerstein** [linux-3ds/linux#59]
I think the title says it all.
Would be nice if it existed but if you aren't experienced with using discord, i could help you out. my ID is mueller_minki#0993 so feel free to dm me about it.

**Comment by ParzivalWolfram** [comment]
You're missing a digit in your provided handle...

**Comment by FreddyFeuerstein** [comment]
sorry, its #0993

**Comment by ParzivalWolfram** [comment]
Discord handles end in 4 digits, not 3.

**Comment by Wolfvak** [comment]
either way, we mostly talk on the GodMode9 discord server (#linux channel, or #3ds-linux on libera.chat)
