### ISSUE TITLE
SDIO driver

### ISSUE THREAD

**Issue by Wolfvak** [linux-3ds/linux#6]
The SD bus is based on an old Toshiba design and is basically the same as the one in the DSi, except with a ~67MHz clock rather than ~33MHz. It's well documented in [gbatek](https://problemkaputt.de/gbatek.htm#dsisdmmcprotocolandioports) and is a piece necessary to get WiFi working.

It could be based off the preexisting toshsd or tmio drivers with a few modifications, since our version of the chip has the separate 32bit FIFO.

[x] base driver
[] 32bit transfers
[x?] full SDIO support

**Comment by Wolfvak** [comment]
first updated in https://github.com/linux-3ds/linux/commit/e3ebf779b35107230c37def80a0e356e694ebbc8

despite adding the id corresponding to my wifi card (O3DS XL, SDIO ID 0271:0201) it doesnt work and the ath6kl spits out some errors on boot, but at least it seems to be able to talk to the card (after toggling the needed gpio:4.0)

**Comment by ParzivalWolfram** [comment]
Side note: the bootloader's lower screen info (before the keyboard inits) is off-center on my N3DSXL. I'm unsure what piece of the project is responsible for this, but it may need tweaked to fix that...
![20210404_134303](https://user-images.githubusercontent.com/30007617/113518650-448c5500-954d-11eb-9892-c17e9ae7fd4c.jpg)
