### ISSUE TITLE
Keyboard mode doesn't work

### ISSUE THREAD

**Issue by MedievalStorm** [linux-3ds/linux#62]
Version/Release: Universal Updater linux_3ds Sergi Granell (2020/12/19) [5.10.0+]
Device: Nintendo 3DS (2011) [Europe]

Pressing the "Select" button doesn't switch to keyboard input mode.

The feature is shown in this video: https://www.youtube.com/watch?v=19lAZA8wrkI

**Comment by Wolfvak** [comment]
that's not what this repo is for... check the wiki
