### ISSUE TITLE
logging in as "root" with password "toor" doesn't work

### ISSUE THREAD

**Issue by dark279** [linux-3ds/linux#68]
not sure what to say, it just doesnt work

**Comment by shokifrend007** [comment]
Does it say `Login incorrect` or is there just no response?

**Comment by Wolfvak** [comment]
Post a picture or something? There's not enough info.

**Comment by dark279** [comment]
i figured it out LOL mightve been using an older version
got it on universal updater, the password was apparently root 💀

**Comment by kleo** [comment]
I updated the 3DS Linux entry on Universal-DB https://github.com/Universal-Team/db/pull/55 and https://github.com/Universal-Team/db/pull/56. Including default login on description. I hope this fixes stuff like https://github.com/linux-3ds/linux/issues/68 and https://github.com/linux-3ds/firm_linux_loader/issues/31

![2022-01-20_16-10-58 290_top](https://user-images.githubusercontent.com/13497504/150298954-23154a8b-4efd-498b-9d3c-87138b3b7572.jpg)
![2022-01-20_16-10-58 290_bot](https://user-images.githubusercontent.com/13497504/150298977-7654f1c5-a83f-4b91-b38c-b6f39d855246.jpg)
