### ISSUE TITLE
Hard-coded home dir into config

### ISSUE THREAD

**Issue by ParzivalWolfram** [linux-3ds/linux#7]
https://github.com/linux-3ds/linux/blob/43af8e26420d52a1e2ac8a9a10fff93c0bc296a7/arch/arm/configs/nintendo3ds_defconfig#L150

**Comment by Wolfvak** [comment]
Yeah that's one of the blunders I made while rushing this out. It's already known and in future versions the config file won't have any hardcoded paths or references like this.
