### ISSUE TITLE
/start-weston.sh doesnt work

### ISSUE THREAD

**Issue by InfamousPB** [linux-3ds/linux#77]
after i put the command in, it stops on a line that says "event0 - Nintendo 3DS input: device removedoved.I", and then it cuts off.

**Comment by Coso04** [comment]
> after i put the command in, it stops on a line that says "event0 - Nintendo 3DS input: device removedoved.I", and then it cuts off.

Happened the same thing to Me. 

I start the .sh file, Weston tries to load and then event0 and it hangs there until i power off

**Comment by Wolfvak** [comment]
Our build doesn't even have weston, there's a good chance you have an older, unsupported version of it.
