### ISSUE TITLE
The Password Isn't Showing Up

### ISSUE THREAD

**Issue by ThisIsAMoron** [linux-3ds/linux#78]
When I get to the password nothing shows up when i type on the keyboard, but the username works well the whole time.

**Comment by kleo** [comment]
CLI passwords are not shown as you type like you do when entering a password on a browser. After entering the username just type the password and hit enter.

[Can I activate password feedback on a tty?](https://unix.stackexchange.com/questions/465798/can-i-activate-password-feedback-on-a-tty)

**Comment by ThisIsAMoron** [comment]
I tried typing it out and it would say invalid password.

**Comment by kleo** [comment]
Default log in username: root password: toor

**Comment by ThisIsAMoron** [comment]
Been using that.

**Comment by kleo** [comment]
Where have you installed Linux 3DS from?

**Comment by ThisIsAMoron** [comment]
Universal Updater.

**Comment by kleo** [comment]
I'm on the same latest install from Universal Updater. Try typing in the password more carefully.

**Comment by ThisIsAMoron** [comment]
I will try soon, just getting a game downloaded

**Comment by ThisIsAMoron** [comment]
It worked
