### ISSUE TITLE
sdcard read/write & io errors

### ISSUE THREAD

**Issue by zipthewolf** [linux-3ds/linux#79]
no matter which sdcard or micro sdcard i use, i am unable to mount any sdcard partitions as rw.
in my boot logs i see a lot of IO errors, but i cant track down the problem.
ive been troubleshooting this for a while and just cant fix it, if anyone could provide help, it would be greatly appriciated.

**Comment by Wolfvak** [comment]
Duplicate of https://github.com/linux-3ds/linux/issues/66
