### ISSUE TITLE
what have i to put?

### ISSUE THREAD

**Issue by juliustram123** [linux-3ds/linux#83]
when i put the login and password it asks me that![image](https://user-images.githubusercontent.com/70858772/199119528-265e99d3-e2ac-48e1-bc23-05fb37db6de2.jpeg) what schould i do?
(sry for my bad english😅)

**Comment by shokifrend007** [comment]
You now have a linux shell. You can find tutorials on the web or youtube if you need help.

**Comment by Wolfvak** [comment]
https://github.com/linux-3ds/linux/wiki#log-in
