### ISSUE TITLE
Why are upstream commits from github.com/torvalds/linux not being merged?

### ISSUE THREAD

**Issue by RokeJulianLockhart** [linux-3ds/linux#84]
Per how https://github.com/linux-3ds/linux/compare/master...torvalds:linux:master states that [This branch is 171768 commits behind torvalds:master.](https://github.com/linux-3ds/linux#:~:text=this%20branch%20is%2056%20commits%20ahead%2C%20171768%20commits%20behind%20torvalds%3Amaster.%20), why are upstream commits from https://github.com/torvalds/linux not being merged? The more time that this continues, the less chance that these devices have of being mainlined, right?

**Comment by nickdesaulniers** [comment]
Because the drivers would need to be rebased, which would involve work. If you want to try your hand at it, send us a pull request.

**Comment by ParzivalWolfram** [comment]
Now that MPCore support has been removed from upstream, i'm pretty sure we missed the window, anyway. It's pretty safe to say this has lost all chances of being approved for upstream, and as such, i'm closing the issue. Maybe this can be reopened if MPCore support is readded in the future.
