### ISSUE TITLE
Can’t log in after installing from universal shop

### ISSUE THREAD

**Issue by EinfachEli08** [linux-3ds/linux#86]
I downloaded the Linux image, loader, etc, booted into it, used root and toor as login credentials, but I can’t acces anything. Need some advice on what I should do now
![image](https://github.com/linux-3ds/linux/assets/100494326/405b2c7f-e4bb-4872-b004-109b0f3dcd36)

**Comment by EinfachEli08** [comment]
But how am I able to „use“ this without being able to log into busybox?

**Comment by ParzivalWolfram** [comment]
The keyboard sometimes isn't 100% accurate on XL devices. Keys sometimes
register differently towards the bottom right. The build on the Updater may
also have different credentials, we don't actually control the versions
they upload.

**Comment by Thetruewatergod** [comment]
i have the same problem what do i do

**Comment by ParzivalWolfram** [comment]
I would suggest downloading the latest build from this repo, instead of using the Universal Updater version.

**Comment by kleo** [comment]
I don't have a 3DS on hand to maintain and test the Universal Updater entry. Entry was removed as requested by @ParzivalWolfram here https://github.com/Universal-Team/db/commit/fdc54cb30e34c7e4b611a11968ee710d0837dce7

**Comment by EinfachEli08** [comment]
The discord entry doesn't exist

**Comment by ParzivalWolfram** [comment]
> The discord entry doesn't exist

You have to be in the universal updater server to see the post.

**Comment by EinfachEli08** [comment]
Oh, so they removed it, interesting

**Comment by Wolfvak** [comment]
Everyone else can log in with root/toor, my guess is you have an incorrect image or something - since you can input "root" its fair to say you can input "toor" even if you don't see it.
I'd say keep trying and if you get anything else open another issue.
