### ISSUE TITLE
glitched screen on boot (3DS xl)

### ISSUE THREAD

**Issue by Poyoio** [linux-3ds/linux#89]
hi! 

I followed all the steps and put the archives in their respectives locations, but when i load de linux firm (payload) i got stuck in this screen:

https://i.imgur.com/NctGCgZ.png

what am i doing wrong?

**Comment by ParzivalWolfram** [comment]
Are you using the right versions of the files? There is a hardware difference between the old and new consoles, and not all consoles branded "new" have the extra hardware. You could try the CTR files, as they seem to work for both, and would rule out a few things.

**Comment by Poyoio** [comment]
this is the files that i am using right now:

![image](https://github.com/linux-3ds/linux/assets/115791454/2b4c4057-b34f-4309-9b92-79469313df9a)

**Comment by ParzivalWolfram** [comment]
Those are abnormally small. The files are corrupted, try copying them over
to the SD card again.

**Comment by Poyoio** [comment]
yeah, now works fine xd

ty!!
