### ISSUE TITLE
bottom screen uninitialized, virtual keyboard missing

### ISSUE THREAD

**Issue by nickdesaulniers** [linux-3ds/linux#9]
I haven't checked to see if there's simply a config that accidentally got disabled or what, but the first time booting this fork I noticed the bottom screen was uninitialized (all different colored pixels) and the virtual keyboard didn't exist, so I had no means of input.  Was this intentionally disabled @Wolfvak ?

**Comment by Wolfvak** [comment]
yeah depending on your bootloader vram might be uninitialized and the framebuffer contains garbage for a while between the point that the screens starts displaying it and linux clears it for the first time to render the software keyboard.

realistically, we'd first get the PDC (PICA Display Controller, basically the CRTC) driver working and that'd manage these things for us

**Comment by nickdesaulniers** [comment]
PEBKAC; after rebuilding everything from scratch everything was fine. I think somethings wrong with the Makefiles for firm loader; make clean && make gives a different sha1 sum after git pulling updates.
