### ISSUE TITLE
Kernel Panic on boot

### ISSUE THREAD

**Issue by Midnite59** [linux-3ds/linux#95]
Whenever I boot, I get the “Failed to mount VFS” error, as well as a kernel panic. I cannot even make it to the log in screen.

I am using the precompiled binaries, because I run windows on my main pc.

**Comment by toast350** [comment]
I am also having the same problem, also happened when compiling. It might be a problem with the initramfs.

**Comment by ParzivalWolfram** [comment]
Please include the model of DS you have, and the MD5 or SHA1 checksums of both the FIRM loader and the initramfs, and I'll look into it. Additionally, a photo of the visible part of the kernel panic would be helpful (a clear recording of the entire boot process even more so.)

**Comment by toast350** [comment]
`93f6919e8d1648d937a52cc8b260a05c5419c050  3dsSD/linux/zImage`
`7189f5055224a39814acf4d1331a6ca4847ba8f5  3dsSD/luma/payloads/firm_linux_loader.firm`

https://imgur.com/a/D1f0zej

**Comment by ParzivalWolfram** [comment]
> `93f6919e8d1648d937a52cc8b260a05c5419c050 3dsSD/linux/zImage` `7189f5055224a39814acf4d1331a6ca4847ba8f5 3dsSD/luma/payloads/firm_linux_loader.firm`
> 
> https://imgur.com/a/D1f0zej

Your build of the loader, at least, is ancient. Where did you get these files? At current, it's not easily possible to build the loader firmware due to https://github.com/linux-3ds/firm_linux_loader/issues/39 but I have attached a new initramfs and set of DTBs for you to try.
[initramfs.cpio.gz](https://github.com/user-attachments/files/16422159/initramfs.cpio.gz)
[dtb.tar.gz](https://github.com/user-attachments/files/16422164/dtb.tar.gz)

**Comment by toast350** [comment]
thanks, I got them from the github release pages.

**Comment by toast350** [comment]
Still gets the same kernel panic, I also tried with compiling everything instead of getting the files from the releases.

**Comment by toast350** [comment]
Nevermind, documentation said to put rootfs.cpio.gz in the kernel tree, but I guess the loader gets the initramfs instead of embedding it into the kernel. I fixed it by putting the initramfs in the linux directory on the SD.

**Comment by ParzivalWolfram** [comment]
That would do it. I do plan on fixing that at some point, but it's been flaky with DTB/initramfs appended. You also no longer need the initramfs appended to the kernel to build it in my personal forks, but those aren't guaranteed buildable at any point.
