### ISSUE TITLE
Black screen after booting loadlinuxfirm.firm

### ISSUE THREAD

**Issue by kijetesantakalu042** [linux-3ds/linux#96]
When I try to run linux it gives me a black screen and turns off when I press a button. I've followed the guide and have all of the files in the linux folder

**Comment by kijetesantakalu042** [comment]
I forgot one of the files I needed, now I can boot but it tells me that it can't mount root fs

**Comment by ParzivalWolfram** [comment]
Please take a photo of the console after the crash happens. Where did you get the files, and which hardware revision do you have?

**Comment by kijetesantakalu042** [comment]
I don't have a working camera to take a picture of my NA New 3DS XL. It goes through multiple lines of numbers and characters and then give the message:
 `
SMP: failed to stop secondary CPUs
---[ end Kernel panic - not synching
: VFS : Unable to mount root fs on unknown-block(0,0) ]---
`

**Comment by kijetesantakalu042** [comment]
I got these files from the github release page:
![image](https://github.com/user-attachments/assets/d6d28996-97eb-425d-bc9d-f56388e68328)

**Comment by ParzivalWolfram** [comment]
I'll put together a test build using my WIP buildroot rework and send a version for you to test when I get some free time.

(Additionally, if you're using the New revision hardware, remove the `nintendo3ds_ctr.dtb` file, as that's for the old revision)

**Comment by ParzivalWolfram** [comment]
I've just remembered: "rootfs.cpio.gz" needs to be renamed "initramfs.cpio.gz" to work with the release version of firm_linux_loader. It's been a bit since i've looked at this project, my apologies for forgetting.

**Comment by kijetesantakalu042** [comment]
Thanks. That worked
